#!/usr/bin/env bash

system_type=$(uname -s)

install_package() {
  if [ "$system_type" = "Darwin" ]; then
    brew install $1
  else
    yay -S --noconfirm --needed $1
  fi
}

setup_zsh() {
  install_package zsh
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
}

setup_tmux() {
  install_package tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

setup_nvim() {
  install_package nvim
  git clone https://github.com/caiohsr14/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
}

install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

if [ "$system_type" = "Darwin" ]; then
  install_brew
  brew install --cask font-meslo-lg-nerd-font
else
  install_package kitty
  install_package btop
  install_package cmake
  install_package pamixer
  install_package thunar
  install_package tofi
  install_package ttf-jetbrains-mono-nerd
  install_package ttf-opensans
  install_package yazi

  install_package grimblast
  install_package hyprland
  install_package hypridle
  install_package hyprlock
  install_package hyprpaper
  install_package hyprpicker
  install_package mako
  install_package waybar
  install_package wl-clipboard
  install_package xdg-desktop-portal-gtk
  install_package xdg-desktop-portal-hyprland

  install_package mpd
  install_package mpdscribble
  install_package mpv
  install_package obs-studio
  install_package pavucontrol
  install_package rmpc-git
  install_package spotify
  install_package telegram-desktop
  install_package thunderbird
  install_package vesktop-bin
  install_package vivaldi

  install_package rainfrog
  install_package sqlitebrowser
  install_package docker
  install_package docker-compose
fi

setup_zsh
setup_tmux
setup_nvim

install_package bat
install_package fzf
install_package fd
install_package eza
install_package lazygit
install_package ripgrep
install_package keepassxc
install_package syncthing
install_package zoxide
